name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/cybertruck/
    - assets/cybertruck/example/
    - assets/model3/
    - assets/model3/example/
    - assets/model3-2024-base/
    - assets/model3-2024-base/example/
    - assets/model3-2024-performance/
    - assets/model3-2024-performance/example/
    - assets/modely/
    - assets/modely/example/
    - assets/modely-2025-base/
    - assets/modely-2025-base/example/
    - assets/modely-2025-performance/
    - assets/modely-2025-performance/example/
    - assets/modely-2025-premium/
    - assets/modely-2025-premium/example/
    - assets/modely-l/
    - assets/modely-l/example/
